#ifndef __ATTESTATION_CONFIG_H__
#define __ATTESTATION_CONFIG_H__

#define DYNAMIC_MEMORY_SIZE (4096 * 100) /* 400KB */

#define HASH_BLOCK_BITS     (256)
#define SYMMETRIC_KEY_BITS  (256)
#define ASYMMETRIC_KEY_BITS (2048)
#define ECP_KEY_BITS        (255)


#endif /* __ATTESTATION_CONFIG_H__ */
